# Generated by Django 4.0.4 on 2022-06-15 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dda1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Person',
        ),
    ]
