# Generated by Django 4.0.4 on 2022-06-15 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dda1', '0003_persons'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
