# Generated by Django 4.0.4 on 2022-06-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dda1', '0004_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cnt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userCount', models.IntegerField()),
            ],
        ),
    ]
