# Generated by Django 4.0.4 on 2022-06-18 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dda1', '0005_cnt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cnt',
        ),
    ]
