# Generated by Django 4.0.4 on 2022-06-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dda1', '0006_delete_cnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='pasn',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
