# Generated by Django 4.0.4 on 2022-06-18 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dda1', '0007_persons_pasn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persons',
            name='pasn',
        ),
    ]
