# Generated by Django 4.0.4 on 2022-06-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dda1', '0008_remove_persons_pasn'),
    ]

    operations = [
        migrations.CreateModel(
            name='reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pasn1', models.CharField(default=0, max_length=100)),
                ('pasn2', models.CharField(default=0, max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='persons',
            name='pasn',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
