# Generated by Django 4.0.4 on 2022-07-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dda1', '0009_reg_persons_pasn'),
    ]

    operations = [
        migrations.CreateModel(
            name='admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminname', models.CharField(max_length=100)),
                ('roomnum', models.CharField(max_length=100)),
                ('reso', models.TextField()),
            ],
        ),
    ]
